export const baseColors = {
  red: '#DC2626',
  white: '#FFFFFF',
  black: '#000000',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  gray700: '#374151',
  gray800: '#1F2937',
  gray900: '#111827',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  info: '#3B82F6',
};

export const lightTheme = {
  background: baseColors.gray50,
  surface: baseColors.white,
  primary: baseColors.red,
  primaryText: baseColors.white,
  text: baseColors.gray900,
  textSecondary: baseColors.gray600,
  textMuted: baseColors.gray400,
  border: baseColors.gray200,
  success: baseColors.success,
  warning: baseColors.warning,
  danger: baseColors.danger,
  info: baseColors.info,
};

export const highContrastTheme = {
  background: baseColors.white,
  surface: baseColors.white,
  primary: baseColors.black,
  primaryText: baseColors.white,
  text: baseColors.black,
  textSecondary: baseColors.black,
  textMuted: baseColors.gray800,
  border: baseColors.black,
  success: baseColors.black,
  warning: baseColors.black,
  danger: baseColors.black,
  info: baseColors.black,
};
