import pytest
import jwt
from fastapi import HTTPException
from app.api.deps import verify_supabase_token, SUPABASE_URL
from fastapi.security import HTTPAuthorizationCredentials

def test_jwks_requires_live_token():
    """
    Why a live token is required for this test:
    
    1. The JWKS flow (PyJWKClient) actively fetches the public keys from:
       https://<PROJECT_REF>.supabase.co/auth/v1/.well-known/jwks.json
       
    2. To verify a JWT, the token header must contain a `kid` (Key ID) that exactly 
       matches one of the keys published on that live Supabase endpoint.
       
    3. The token signature must be mathematically valid for the public key (ECC P-256 / ES256) 
       hosted at that URL. 
       
    4. Therefore, it is impossible to "mock" a valid token for this specific test without 
       either mocking the entire HTTP request to the JWKS endpoint OR having a real token 
       generated by the live Supabase Auth server.
       
    This test verifies that an invalid token correctly throws an HTTPException indicating 
    an invalid signature/format, proving the verifier is active.
    """
    
    # A completely fake token that does not have a valid ES256 signature
    fake_token = "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImZha2Uta2lkIn0.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.fake_signature_that_will_fail"
    
    credentials = HTTPAuthorizationCredentials(scheme="Bearer", credentials=fake_token)
    
    with pytest.raises(HTTPException) as excinfo:
        verify_supabase_token(credentials)
        
    # The exception should be a 401 Unauthorized because the PyJWKClient will fail 
    # to find the key, or the signature will be invalid.
    assert excinfo.value.status_code == 401
    assert "Invalid authentication credentials" in excinfo.value.detail
